services:
  i1s3:
    build:
      context: .
      dockerfile: i1s3.dockerfile
    image: nowage/i1s3:oraclelinux9

  i1:
    build:
      context: .
      dockerfile: i1.dockerfile
    container_name: i1
    hostname: i1
    networks:
      - hnet
    volumes:
      - ./df/i1:/df
    tty: true
    depends_on:
      - i1s3
      - s1
      - s2
      - s3
    # command: /root/setup-ssh.sh

  s1:
    build:
      context: .
      dockerfile: s.dockerfile
    container_name: s1
    hostname: s1
    networks:
      - hnet
    ports:
      - "2221:22"
      - "8080:8080"
      - "4040:4040"
      - "8081:8081"
      - "8000:8000"  # 추가: exporter용
    volumes:
      - ./df/s1:/df
    tty: true
    depends_on:
      - i1s3
  s2:
    build:
      context: .
      dockerfile: s.dockerfile
    container_name: s2
    hostname: s2
    networks:
      - hnet
    ports:
      - "2222:22"
      - "8082:8081"
    volumes:
      - ./df/s2:/df
    tty: true
    depends_on:
      - i1s3
  s3:
    build:
      context: .
      dockerfile: s.dockerfile
    container_name: s3
    hostname: s3
    networks:
      - hnet
    ports:
      - "2223:22"
      - "8083:8081"
    volumes:
      - ./df/s3:/df
    tty: true
    depends_on:
      - i1s3
  m1:
    build:
      context: .
      dockerfile: m1.dockerfile
    container_name: m1
    hostname: m1
    networks:
      - hnet
    ports:
      - "9090:9090"  # Prometheus
      - "3000:3000"  # Grafana
    volumes:
      - ./df/m1:/df
      - ./df/m1/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - i1s3
networks:
  hnet:
    external: true
