---
- name: Set up passwordless SSH for Hadoop Cluster
  hosts: hadoop_cluster
  become: yes
  tasks:
    - name: Ensure SSH key pair is present
      ansible.builtin.file:
        path: /root/.ssh/id_rsa
        state: file
      ignore_errors: yes

    - name: Generate SSH key pair if not exists
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa

    - name: Copy SSH public key to other hosts
      ansible.builtin.shell: |
        sshpass -p '{{ ansible_ssh_pass }}' ssh-copy-id -o StrictHostKeyChecking=no root@{{ inventory_hostname }}
      vars:
        ansible_ssh_pass: "root_password_here"
